"""Execution limits and defaults for automated simulation batches."""

ONLY_DETERMINISTIC = "Only Deterministic"
ONLY_LLM = "Only LLM"
COMPARISON = "Deterministic vs LLM"
BATCH_MODES = (ONLY_DETERMINISTIC, ONLY_LLM, COMPARISON)

DEFAULT_DETERMINISTIC_BATCH_SIZE = 1000
DEFAULT_LLM_BATCH_SIZE = 10
DEFAULT_COMPARISON_BATCH_SIZE = 20

MAX_DETERMINISTIC_BATCH_RUNS = 1_000_000
MAX_LLM_BATCH_RUNS = 1000

FIXED_DELTA_TIME = 1.0 / 60.0
MAX_SIMULATED_SECONDS = 180.0
